# Generated by Django 5.0.7 on 2024-07-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_cliente_correo_cli_alter_producto_precio_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto_id_dv',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='total_linea',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta_id_dv',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='moneda_vta',
            field=models.CharField(choices=[('BS', 'Bolivianos'), ('USD', 'Dolares')], default='BS', max_length=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_vta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
