# Generated by Django 5.0.7 on 2024-07-28 16:01

import django.core.validators
import inventario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_producto_detalleventa_producto_id_dv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_cli',
            field=models.CharField(max_length=255, validators=[inventario.validators.validarEmail]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_cli',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'El documento debe ser minimo de 4 caracteres')]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario_dv',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validation_numero]),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_inv',
            field=models.IntegerField(validators=[inventario.validators.validation_numero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_pro',
            field=models.IntegerField(validators=[inventario.validators.validation_numero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_pro',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[inventario.validators.validation_numero]),
        ),
    ]
